#!/bin/sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

KEYGRIP_GPG_SUB_S="28F4330AF3EC149AE0B1C1645A8F6AD8D390260C"
KEYGRIP_GPG_SUB_E="BCEEB5A1B3447693212422BBD0156965BE71AE73"
KEYGRIPS_GPG="$KEYGRIP_GPG_SUB_S $KEYGRIP_GPG_SUB_E"


cache_key_passphrases () {
  killall -q -u $USER ssh-agent; ssh-agent > $HOME/.ssh-agent.socket ; . $HOME/.ssh-agent.socket
  killall -q -u $USER gpg-agent; gpg-agent --daemon --allow-preset-passphrase --default-cache-ttl 31536000 --max-cache-ttl 31536000
  while true; do
    read -p "Cache passphrase for keys: " -s passphrase; echo
    
    expect <<-EOF
      log_user 0
      spawn ssh-add
      expect { 
        "Enter passphrase for $HOME/.ssh/id_rsa:" { send "$passphrase\r" }
      }
      expect {
        "Bad passphrase, try again for $HOME/.ssh/id_rsa:" { exit 1 }
        eof
      }
EOF

    if [ $? -eq 0 ]; then
      for keygrip in $KEYGRIPS_GPG; do
        echo $passphrase | /usr/lib/gnupg/gpg-preset-passphrase --preset $keygrip
      done
      break;
    fi
  done
}

start_x () {
  while true; do
    read -p 'Do you want to start X? [Yn]: '
    case $REPLY in
      [Yy]|"")  startx 1> ~/log/x.out ; vlock ;;
      [Nn])     break ;;
      *)        printf '%s\n' 'Please answer y or n.' ;;
    esac
  done
}

start_kodi () {
    kodi-standalone
}


if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

bluetoothctl << EOF
power on
EOF

cache_key_passphrases

killall -q -u $USER udiskie; udiskie &

killall -q -u $USER afuse; afuse    -o mount_template="sshfs %r:/ %m" \
                                    -o unmount_template="fusermount -u -z %m" \
                                    -o timeout=20 \
                                    ~/mnt/ &

if [[ $XDG_VTNR -eq 1 ]] ; then
    which X &> /dev/null
    if [[ $? -eq 0 && -z $DISPLAY ]] ; then
        start_x
    else
        start_kodi
    fi
fi
