#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
[ -f ~/.xbindkeysrc ] && killall -q -u $USER xbindkeys; xbindkeys
start-pulseaudio-x11
xrandr --output LVDS1 --primary --mode 1680x1050 --pos 0x0 --output DP1 --off --output VGA1 --mode 1920x1200 --pos 1680x0
xcompmgr &
killall -q -u $USER conky; conky 1> ~/log/conky.out 2> ~/log/conky.err &
xscreensaver -no-splash &
keepassxc &
dropbox &

exec awesome
