#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
[ -f ~/.xbindkeysrc ] && killall -q -u $USER xbindkeys; xbindkeys
start-pulseaudio-x11
xrandr --output LVDS1 --primary --auto --output DP1 --off --output VGA1 --auto --above LVDS1
xcompmgr &
killall -q -u $USER conky; conky 1> ~/log/conky.out 2> ~/log/conky.err &
xscreensaver -no-splash &

exec awesome
