#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources
[ -f ~/.xbindkeysrc ] && killall -q -u $USER xbindkeys; xbindkeys
xcompmgr &
killall -q -u $USER conky; conky 1> ~/log/conky.out 2> ~/log/conky.err &
xscreensaver -no-splash &

exec awesome
